### ISSUE TITLE
README.md: pip3 install --local pipenv does not work.

### ISSUE THREAD

**Issue by bulwahn** [lfd/PaStA#1]
I believe the command "pip3 install --local pipenv" does not work; at least, it did not work on an Ubuntu 18.04 system.
"pip3 install pipenv" did the job; possibly you mean the option "--user"?

**Comment by rralf** [comment]
Ah, yes, thanks for reporting.

Maybe I mixed up --local (even non-existent?) and --user. Let me double check that on a vanilla system; I don't use pipenv on my local machine, as all required packages are provided by my distribution.

BTW: I'll try to get rid of some dependencies anytime soon, esp. some unmaintained flask dependencies to mitigate the python dependency hell.

**Comment by rralf** [comment]
Fixed on next in 232e3b02f. I removed the Pipfile -- the fewer dependencies, the better. Taking Ubuntu 18.04 LTS as a reference, almost all packages are provided by the distribution, so let's use them. Only two must be installed via pip at the moment, but they will be reduced in future.

I'm also considering to use Travis CI for continuous integration... Let's see...

Thanks for reporting!
