### ISSUE TITLE
Demonstrate PaStA capabilities for interested visitors

### ISSUE THREAD

**Issue by bulwahn** [lfd/PaStA#13]
Motivation: Before interested visitors would setup PaStA, they would like to see the capabilities of PaStA with a demonstrator. This would generally increase and simplify the outreach for this project.

Task: Provide some demonstrators for PaStA's functionalities

Examples:
  - Provide a dashboard service of insights from implemented analysis in Pasta 
  - Provide a public service (Web frontend) of the Pasta result
  - Provide a yearly report where the analysis with PaStA are interpreted, and changes that can be identified with PaStA are described, interpreted and explained.

In the discussion of the example of a dashboard service identified that it is challenging to provide a useful dashboard service, as most metrics cannot be considered in isolation, but it requires an expert interpretation and judgement of various metrics to come to a proper interpretation.

**Comment by rsarky** [comment]
Being a new visitor this would be really amazing. Currently while trying to explore PaSta I would love it if there was an analysed repository also available that I could play with. 

I am facing some issues currently following the instructions in the README to analyse an existing repo.
For eg. analysing the linux repository is taking a tremendous amount of time. Maybe it might be better if we analyse a smaller repository for demo purposes instead ( say jailhouse, ~2706 commits).
I am currently working on running PaSta on jailhouse. And can document the steps I took to make it work
