### ISSUE TITLE
Provide an overall configuration state summary

### ISSUE THREAD

**Issue by bulwahn** [lfd/PaStA#17]
Considering executing an analysis, there are several different input sources, internal cache states that are constructed to previous runs and an evolving implementation. All of those factors, that could be considered _the configuration state_ on which an analysis is based on, lead to slightly different results when executing an analysis on slightly different configurations.
In order to clearly and unambigiously determine this configuration state, specifically for the purpose of providing analysis results to others that then independently may reproduce them with the same outcome, pasta should report a short `configuration state summary` that mentions short unique identifiers of the overall configuration state.

I would imagine that it needs to report:
 - the sha identifier of the pasta source git repository (or some pasta release version number) 
 - the relevant parts of the config file, if not covered by the further information in this list
 - the sha identifiers of all the public-inbox git repositories
 - a hash for each raw mbox file
 - a hash of the mail index
 - a hash of the caches
 - and probably some further hashes of some internal processing that is reused from one analysis to the next.

The ultimate goal would be that:
1. Given that configuration state summary, it is possible to re-create the same configuration for an analysis. e.g., on a different system or by a second user.
2. when the configuration state summary is completely identical, the analysis with pasta will produce exactly the same results.

**Comment by rralf** [comment]
Hi Lukas,

I totally support this idea, but there are some obstacles:

>  the sha identifier of the pasta source git repository (or some pasta release version number)

That's not enough for some reasons:
- External, untracked data sources might be used (raw mailboxes or external repos)
- Tracked data sources (git submodules, such as the code repos themselves, or public inboxes) might be dirty. Adding a -dirty flag to the analysis just tells you that you don't know what exact data was used for analysis.

>    the relevant parts of the config file, if not covered by the further information in this list

If not further modified, the config file is tracked by the resources repository.

>    the sha identifiers of all the public-inbox git repositories

If not further modified, it is already tracked by the submodule-hash of the resources repo.

>    a hash for each raw mbox file

Ack, that should really be tracked. But hey, there's an alternative. PaStA parses raw mailboxes and splits them up to single files. Now there are two possibilities how we this *could* be changed:
- Add those mail files, including the index for raw mailboxes to the resources repo. But this will blow up the repository extremely. I already have some issues pushing large files to github. Yet unsure if this is a good idea.
- Convert mboxes to public inboxes. Then we have unique commit hashes that we simply include as submodule like we do it with all other public inboxes. With this, we could also eliminate the 'raw mailbox' interface.

>    a hash of the mail index

If not further modified, it is tracked by the resources submodule.

>    a hash of the caches

Caches should be irrelevant for the result.

> and probably some further hashes of some internal processing that is reused from one analysis to the next.

Ideally, everything should be added to the resources submodule. This includes sub-submodules. With this, the unique hash of the resources submodule should be sufficient. A -dirty flag could indicate the unreproducability of the result.

BTW: PaStA concatenates all output to a logilfe in the working directory of PaStA, called `log`. We can also create separate logfiles for every single run of pasta and add it to the resources repo.

**Comment by bulwahn** [comment]
Good idea and it solves the issue. I need to understand and then create documentation on:

- how to set up a public inbox git repository and how to initially fill and update a public inbox git repository from a continuous offlineimap export.

Let me see how I will make progress on that engineering challenge.
