### ISSUE TITLE
Investigate matching alternatives for diff hunk header

### ISSUE THREAD

**Issue by bulwahn** [lfd/PaStA#19]
Currently, the matching in pasta requires the diff hunk header of patches and commits to 100% identical to be matched against each other.

The investigation on off-list patch detection showed a number of cases where matching failed due to the diff hunk header being different:
  - it seems that some patches are created where the patches are cut off after 40 characters
  - sometimes the line of the diff hunk header is refactored between patch creation and inclusion

With these insights, we might find a better compare function and threshold to match patches and commits.
At first, we would need to identify all patches that might be matched with alternatives for the diff hunk header and estimate to which differences this leads and what improves and what possibly decreases.

**Comment by rralf** [comment]
> Currently, the matching in pasta requires the diff hunk header of patches and commits to 100% identical to be matched against each other.

There's the '-th' parameter (hunk header threshold) to control the sensitivity of the similarity.

For the rest, ack, this needs investigation if there are better methods of comparison.

**Comment by bulwahn** [comment]
This looks like a first good exercise for a newcomer that wants to gets started with pasta. I still need to collect all the examples I found, but then somebody could have a first look on this topic.
