### ISSUE TITLE
Determine who picks up patches to certain files vs. who is the documented maintainer in MAINTAINERS

### ISSUE THREAD

**Issue by bulwahn** [lfd/PaStA#20]
Motivation:

This would allow to show to which extent the MAINTAINERS file reflects the current practice and the mismatch.

Open question:
Does this even need the mailing list, or could this be determined just by considering the git history, i.e., the git committer of each commit and the MAINTAINERS file?

**Comment by rralf** [comment]
Hmm. It might be sufficient to look at Signed-off-by tags or/and the committer of the patch. Mailinglists could help, as they reveal if a maintainer was involved in the discussion at all.

**Comment by bulwahn** [comment]
This task is really just comparing the Signed-off information of the git commits and the information that get_maintainers.pl would suggest. A very small python script would allow to gather this information and the crucial part is aggregate the mismatches in a useful way to make conclusions.

**Comment by bulwahn** [comment]
I think we can make use of gitdm here to understand who picked up a patch, i.e., in which merge tree did it land first.
