### ISSUE TITLE
Linux Kernel Internship - Patch Trace Analysis with PaStA

### ISSUE THREAD

**Issue by tapaswenipathak** [lfd/PaStA#29]
Hi folks, As linked and told on email, I am interested in the linux kernel internship  **Patch Trace Analysis with PaStA**,  as the linux kernel internship deadline is in next few days, I will be using this ticket where ever required as this is just one present on GitHub. Sincere apologies for any extra work required as I don't think we would get a lot of time for interactions. As I don't require most of the listed mentee application activities, I will directly work on the tickets listed. Thanks a lot, Tapasweni!

(1) https://wiki.linuxfoundation.org/lkmp/lkmp_project_list

**Comment by bulwahn** [comment]
If you would like to work on this project, I suggest that we look into #20 and #21 as quick starters.

**Comment by bulwahn** [comment]
Actually, #20 is probably best to get really quickly started.

**Comment by tapaswenipathak** [comment]
Thanks @bulwahn, appreciate the effort for suggesting tickets.
