### ISSUE TITLE
[GSOC] Add a requirements.txt to make setup easier

### ISSUE THREAD

**Issue by rsarky** [lfd/PaStA#39]
I was trying to setup PaSta on my local and was getting various errors related to dependencies not being there on my system. I think a `requirements.txt` would be a step towards streamlining the setup process.

**Comment by rralf** [comment]
There's a requirements section in README.md. Is there anything missing? Patches welcome!

**Comment by rralf** [comment]
Ah, and we have the dockerfiles were all requirements should be listed.

**Comment by rsarky** [comment]
I was getting some 
"Module not found" 's even when I installed the dependencies in the readme.
Maybe I can create a fresh python env through conda and see if installing the dependencies in the readme is enough to get started?

**Comment by rsarky** [comment]
Oh I see, one of the discrepancies is that in the docker file you are installing the python package dateparser whereas that's been omitted in the readme. I had to do a pip3 install dateparser to make it work. Can submit a PR to fix this

**Comment by rralf** [comment]
I think dateparser is mentioned in the README, though. But the apt install command in the README seem to not reflect reality. Maybe the solution is to point to the dockerfile in the README. Then we only have docker as the single source of truth. I think there's no need for that redundancy. Thanks!

**Comment by rsarky** [comment]
Makes sense
