### ISSUE TITLE
Readme mentions 4 steps but only 3 are explicitly mentioned

### ISSUE THREAD

**Issue by rsarky** [lfd/PaStA#43]
This is probably a minor documentation quirk
According to the README: `The detection phase is split in four steps:`
But there are only 3 explicitly mentioned steps.

**Comment by rralf** [comment]
You're right, I can also only count 3. Off by one. :-)

Uhm, other than that, step one only makes sense in PatchStack mode (PaStA is also able to compare repositories against each other). The Mbox support was an extension that was later added to PaStA.

**Comment by rsarky** [comment]
> Uhm, other than that, step one only makes sense in PatchStack mode (PaStA is also able to compare repositories against each other). The Mbox support was an extension that was later added to PaStA.

Took some time for me to figure that out by myself. Should probably document that for other users.
Also how do you generate the `patch-stack-definition.dat` files used in PatchStack mode?

> PaStA is also able to compare repositories against each other

Do you mean compare revisions against each other here? What does comparing repositories mean exactly?

**Comment by rralf** [comment]
Hah... Good question!
That's a semi-automatic step at the moment. 
There's a script, update-preemptrt.sh It downloads all new stacks, applies them on separate branches and creates a file called 'psd'. I'm then filling out missing entries in that file, and merge entries with the patch-stack-definition.dat. But no need to go into this direction.

This is the way how PaStA initially used to work. Support is still there, but we focused on mailing list analysis after a while. If you're interested why and what we did in the PreemptRT project, you can have a look here: https://arxiv.org/abs/1607.00905

**Comment by rsarky** [comment]
> This is the way how PaStA initially used to work. Support is still there, but we focused on mailing list analysis after a while.

Seems like I am missing a bit of historical context that's tripping me up.

>  If you're interested why and what we did in the PreemptRT project, you can have a look here: https://arxiv.org/abs/1607.00905

Will give it a read. Thanks!

**Comment by rralf** [comment]
And we can close this one.
