### ISSUE TITLE
Identify and evaluate ignored/re-submitted patches

### ISSUE THREAD

**Issue by bulwahn** [lfd/PaStA#5]
Motivation: Ignored patches in the kernel development can indicate process weaknesses in the Linux kernel development. These must be identified for a proper assessment of the process strength of the kernel development, e.g., for trustable software.

This issue can be split into the following two tasks:

**Task 1: Extend Pasta such that the following two classes of patches can be identified.**

As first approximation, an ignored patch is defined as follows:

- The patch has been provided to the mailing list.
- The patch was not included in the git repository
- The patch was not discussed on the mailing list

Further, an re-submitted patch is defined as follows:

- The first patch has been provided to the mailing list.
- The first patch was not discussed on the mailing list
- A similar patch was re-submitted to the mailing list by a second person
- The second patch was included into the git repository

Given a Pasta project definition (mailing lists and git repositories), Pasta shall be extended to provide the list of patches according to those definitions above. 

**Task 2: Evaluate ignored and re-submitted patches for the Linux kernel development**

With the identification of ignored and re-submitted patches at hand, we want to evaluate the current kernel development.

The evaluation shall produce a written report to be published as a technical report/white paper/scientific publication (to a Linux-development related/empirical software engineering-related workshop/conference).

The evaluation shall include:

- the absolute number of patches in the kernel development over time (for the last ten years and as far as lore.kernel.org data is available) for the two categories (ignored, re-submitted)
- the relative number of patches for the two categories compared to the absolute number of patches over time
- interpretation of the trending of that development over time
- differentiation of this data according to the Linux kernel subsystems
- refinement of the data to three relevant product kernel configurations (refinement can probably be done using the patch-impact tester)
- classification of ignored and re-submitted patches to determine the root cause. Categories shall be critical bug fixes (with determination of CWE if applicable), optimisations, features or stylistic changes, i.e., documentation, code style issues, code readability, patch conflicts, i.e., the patch could not be applied due to another change that happened in parallel.
- interpretation of the data after the classification with recommendations to the three relevant product kernel configurations and the Linux kernel development in general
- evaluation if the determined ratios for the subsystems are in line with the expert opinion and community recognition of subsystem maintainers, e.g., overload of maintainer, maintainer policy, through an email/online questionnaire and interview session on a Linux kernel conference, e.g., Linux plumbers.

**Comment by bulwahn** [comment]
Currently, the pasta "mail cache" structure does not include the responses to patches. To implement this feature, we would need to have that information available.

I see two ways to get there:
1. we include all mail responses as substructure to the according patch in the existing datastructure. Currently, pasta already requires significant memory storage and this will even increase by yet another factor with this change.
2. we refactor the mail cache to be a suitable database and then add this functionality; this could lower the large memory needs.

@rralf What is your take on this?

**Comment by rralf** [comment]
Yes, the commit cache (i.e., patch cache) doesn't contain those mails as they don't contain patches. The cache is only used for the analysis.

Nevertheless, you can retrieve raw email message objects indexed by their Message-ID.

See this function: https://github.com/lfd/PaStA/blob/next/pypasta/Repository/Mbox.py#L423 
It takes a Message-Id and returns a list of email objects (as Message-IDs aren't unique).

Maybe this already solves (parts of) your problem?

Concerning 1.) and 2.):

  1.) Pasta already requires (too) much memory, and responses aren't required for the actual analysis, so no need to keep them in memory.
  2.) That would be nice of course. I'm not a database expert, and the change to a suitable database heavily depends on its performance and usability. Maybe a simple key-value store (Mongo, Redis) might be more suitable than MySQL, didn't evaluate this. Setting up a database server might also be annoying for users, so this should really be carefully considered.

**Comment by bulwahn** [comment]
Okay, I got it.

For 1.) I think to work on this task, it would require to iterate over all messages and build up the tree of responses to initial mails, simply storing their according Message IDs. I think `Mbox::message_ids(...)` (https://github.com/lfd/PaStA/blob/next/pypasta/Repository/Mbox.py#L435) should be sufficient for iterating and then one could build the tree.

For 2.) I am considering if the patchwork instance already has a suitable database scheme to re-use the same database scheme, possibly some code from there and certainly make it easier to transfer datasets from patchwork to pasta (and eventually back).

**Comment by rralf** [comment]
1.) Et voilà: https://github.com/lfd/PaStA/blob/master/pypasta/Repository/MailThread.py#L162

MailThread::get_thread takes a message-id and gives you the whole tree (values are message-ids). The MailThread class currently has no users, but it's existent.

2.) Could be the case, yes. But I'm concerned if, in our case, databases are the right choice, but let's see.

**Comment by bulwahn** [comment]
Great, so the infrastructure would be in place. We just need make the tool to extract and present the data.
I see that we can simply extend the current codebase. So, for this feature here, there is no immediate need to refactor pasta to have some kind of more advanced database solution than you currently have. I am also not the database expert, I was not just considering SQL but there many alternative data storage, search and retrieval solutions out there, and probably at least one that fits ;)
