### ISSUE TITLE
Support identification of kernel developers for improving the precision of analysis

### ISSUE THREAD

**Issue by bulwahn** [lfd/PaStA#53]
Many kernel developers use multiple different email addresses while engaging on the mailing list and mention different email addresses in the MAINTAINERS file. Hence, statistics that aggregate based on email identities and try to map engagements to roles in MAINTAINERS.
Hence, it would be helpful if we have some support that we can use to uniquely identify a kernel developer and map the various identities to a unique identifier.

We probably should start looking at what Jonathan Corbet does in gitdm to identify developers and make optimal reuse of that. Maybe Wolfgang has also some functionality for that as well?

**Comment by rralf** [comment]
@wolfgangmauerer 

Codeface has its own id-service, bitergia implements, afaik, a similar service.

**Comment by sumana-2705** [comment]
Hello @rralf  @bulwahn 

My name is Sumana, and I am from India. I am interested in participating in the LFX Mentorship program and would love to work with your organization. I have a keen interest in Machine Learning and have completed several projects involving **Data Visualization and ML-based predictions**. I found this repository and believe it aligns well with my skills and interests.

I want to work with this issue. Could you please let me know if this repository is currently active? If it is not, could you suggest any other repositories where I could contribute and further develop my skills?

I am new to contributing I want to explore opensource with my skills. Please help me out.

Thank You

**Comment by rralf** [comment]
Hi,

this project hasn't been under active development for a while, while it's still being used for research activities. I'd suggest to jump on another project.

Thanks,
  Ralf
