### ISSUE TITLE
Update Readme for Getting PaStA

### ISSUE THREAD

**Issue by jay24rajput** [lfd/PaStA#63]
The commands for [Getting PaStA](https://github.com/lfd/PaStA#getting-pasta) state that the following command is required to be executed : 
```
$ ./tools/update_resources.sh # This might take some time to complete
```` 

However, as stated by @rralf it is not necessary for contributors to download all the submodules whose size can get really huge and pretty time-consuming.

## Proposal

Let us add a label/heading for the Command : ```Only for maintainers```.So that it won't confuse future contributors

We could also Add alternatives for testing PaStA such as checking out the ```alsa-minconfig``` for relevant resources

**Comment by rralf** [comment]
Yes, we could move that command to a maintenance section to make it clear.

**Comment by jay24rajput** [comment]
Aright! Will do it! 

Also, Can we have like a ```requirements.txt``` file for downloading the resources directly into the system, without running the dockerfile, with the command 
``` 
pip3 install -r requirements.txt 
```
We can add this command to the **Getting PaStA**  instead of the above command ```./tools/update_resources.sh``` for getting the dependencies directly?

**Comment by rralf** [comment]
Well, the reason why we don't have it: I fear that this would bitrod over time. Whenever a dependency changes, we have to keep those files in sync. If we have a thing like the requirements.txt, the docker file should make somehow use of it.

Other than that, I use pip only for packages that are not available via official resources of your distribution: pip uses latest & greatest package version, while Ubuntu's resources tend to stay on a stable release. I prefer the latter one as I don't want to have breaking library APIs every other day.

**Comment by bulwahn** [comment]
Ralf, I think the README should also point out all our presentations and papers for newcomers to get a basic introduction:
the LPC presentation recording, the ELCE presentation recording, the LWN.net article, Anmol's ELISA Workshop presentation, the papers, the master theses using pasta.

**Comment by bulwahn** [comment]
I will provide a pull request in case I will get to that this week.
