### ISSUE TITLE
Assess usage and impact of tools in the development process

### ISSUE THREAD

**Issue by bulwahn** [lfd/PaStA#8]
**Motivation:**

Concerning testing and verification methods and tools, i.e., static and dynamic analysis, we would like to argue a good coverage of the safety standards’ objectives by the following assessment. We assess the current state and identify gaps through the following three investigations:

1. Assess capabilities of used tools
2. Assess usage/impact of tools in the development process
3. Analyse the output of verification tools on the current codebase 

For the second investigation, we would like to build upon some analysis with Pasta.

**Pre-existing Investigation**

todo: mention Philipp Klocke's work.

**Implementation Task in Pasta**

We would like to determine where patches have been induced to be modified by testing and verification tool output.

Identify those patches with modification due to testing and verification: 
- Based on keywords mentioned in the patch change history
- Based on email responses from automatic testing infrastructure

**Evaluation Task with this data**

With the identification of impact of tool findings, we want to evaluate the current kernel development.

Evaluate and summarize which tools are applied at which stage in the patch submission and integration process.

The evaluation shall produce a written report to be published as a technical report/white paper/scientific publication (to a Linux-development related/empirical software engineering-related workshop/conference).

The evaluation shall include:

- the absolute number of patches in the kernel development over time (for the last ten years and as far as lore.kernel.org data is available) that have been impacted by verification tools.
- the relative number of patches impacted by verification tools to the absolute number of patches over time
- interpretation of the trending of that development over time
- differentiation of this data according to the Linux kernel subsystems
- refinement of the data to three relevant product kernel configurations (refinement can probably be done using the patch-impact tester)
- classification of changes due to tool findings. Categories shall be critical bug fixes (with determination of CWE if applicable), stylistic changes, i.e., documentation, code style issues, code readability.
- interpretation of the data after the classification with recommendations to the three relevant product kernel configurations and the Linux kernel development in general
- evaluation if the determined ratios for the subsystems are in line with the expert opinion and community recognition of subsystem maintainers, e.g., overload of maintainer, maintainer policy, through an email/online questionnaire and interview session on a Linux kernel conference, e.g., Linux plumbers.

**Comment by rsarky** [comment]
Hey Lukas,
Can this issue be considered as somewhat overlapping the project "Develop methods of tracking tool analysis findings over time". [here](https://wiki.linuxfoundation.org/gsoc/2020-gsoc-safety-critical-linux)
I am interested in picking this up too if it's fine with you and @rralf ?
A rough plan about how I intend to go about this is:
1. Make a list of tools that are going to be analysed: sparse, coccinelle etc.
2. Hook into PaStA to identify patches that either 
  a. Are automatically generated by tools. (Eg. bots reporting crashes)
  b. Are explicitly mentioned in the patch by a contributor. Eg. A developer fixing an issue found by coccinelle
3. Make relevant data structures to store the data.
4. Run analysis on the data collected to form various hypotheses
