### ISSUE TITLE
Combine PaStA with the patchwork tool

### ISSUE THREAD

**Issue by bulwahn** [lfd/PaStA#9]
Motivation:
Currently, Pasta is a tool developed by a single developer and only has a small (academic) user base. When we integrate with patchwork, we hope that this significantly increases the interest, user base and eventually the development community around this tool. This will help to keep Pasta maintained and evolve over time.

Task:
Integrate the automatic tracking from PaStA into the WebGUI of the patchwork tool, such that the user can see the different versions of the patches and where it was integrated in the repositories.

Further, it should be possible to show similar patches on the mailing list/git repositories in Patchwork [1]. This indicates concurrent activities on the mailing list.

Possibly, we can also provide these functionalities as a simple command line tool for the kernel developers to inform them about the current state of their patches and to point out similar changes that are happening elsewhere (and where the developer might not been aware). This would then not be integrated in Patchwork, but would be part of PaStA as self-contained tool.

[1] http://jk.ozlabs.org/projects/patchwork/

**Comment by metp** [comment]
TODO
- [ ] REST: Don't allow moving implicitly a submission to another relation
- [ ] Update tests
- [ ] Simple installation & setup instruction
